name: Build Succeeds on PR

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.4
      - name: Install dependencies
        run: bun install
      - name: Lint the project
        run: bun run lint
      - name: Build the project
        run: bun run build
      - name: Check formatting
        run: bunx prettier --check "**/*.{js,jsx,ts,tsx,json,md}"
